### ISSUE TITLE
CMS: clean up

### ISSUE THREAD

**Issue by buddymanga** [varmab/mangahub#19]
- Delete all series with (Delete) in front of the titles name
- Bug: chapter page count not showing in some series' chapter list

![Screen Shot 2019-12-03 at 16.48.02.png](https://images.zenhubusercontent.com/5dacfe023243eb00015ca0a5/474d0b76-80db-4099-86d9-4dac3a644e3a)

**Comment by varmab** [comment]
Duplicate??
