### ISSUE TITLE
v0.0.24 Investor Build Reader bug

### ISSUE THREAD

**Issue by buddymanga** [varmab/mangahub#21]
Investor Build 
Clicking on READ button on any unread Series from Browse:
Blank Black Screen

Touch screen: Chapter error
"NaN/25"

**Comment by buddymanga** [comment]
https://www.dropbox.com/s/0wpdx1h9s81ml2y/RPReplay_Final1575601922.MP4?dl=0

**Comment by varmab** [comment]
Ok We will work on it today.

**Comment by buddymanga** [comment]
Varma

How is the investor build bug fix going?

Also, any luck getting into the CMS?

buddy

On Dec 7, 2019, at 11:04, Varma Bhupatiraju <notifications@github.com> wrote:

﻿

Ok We will work on it today.
