### ISSUE TITLE
Image Loading Lag

### ISSUE THREAD

**Issue by leematsunami** [varmab/mangahub#24]
Reading on the app, swiping between pages, going back to the menu, etc. - in general using the app, the speed of images/pages loading is inconsistent. Some pages take 3-5 seconds to load. Is there something we can do to improve speed on a whole?

**Comment by Sradhanjali170494** [comment]
This issue may require more research. I will update the estimate after replicating the issue.

**Comment by varmab** [comment]
We need to check more in AWS side and may be add CloudFront and optimizations on caching may solve to some extent. However, I won't be able to guarantee. I estimate initially for 4 hours and see what is implemented and try something like CloudFront and check its caching.

**Comment by leematsunami** [comment]
I was just reading manga on my iPad and I experienced the black page again. Just leisurely reading Somali, swiped to page 9 and got nothing but black. I pressed again so I could see the page count on top. I swiped all the way to the end 40/40 and got nothing but black. When I went backwards, the pages appeared.

Don't know if it matters that I was reading on an iPad?

**Comment by mangamojad** [comment]
4 hours approved for research. Please provide the tech approach for optimization before implementing.

**Comment by varmab** [comment]
Based on my research, I found that page images for lot of series has sizes of more than 1 MB around 1.3-1.5MB. 

![image.png](https://images.zenhubusercontent.com/5d051620f51b654fc32e23b5/6c7967b1-a69d-458f-ae94-b4a03d986daf)

It is hard to optimize them unless we reduce them to size less than to around 500KB to improve the performance.  We should make Admin tool to do necessary compression to less than 1MB during upload.
I saw some series has page image sizes less than 1MB. They should be loading fine.

![image.png](https://images.zenhubusercontent.com/5d051620f51b654fc32e23b5/8e747af3-e48e-4180-8094-502d6792e85e)

**Comment by mangamojad** [comment]
We cannot go lower in size as this size is already the optimal size for readability. Remember, there is text on these images that are zoomed in. If we go any lower then we will compromise the quality of that text. In addition, to resize all of these images will be an expensive effort. We're looking at over 1000+ images. This is not cost or time effective.

We will have to brainstorm on a different approach. I will look into alternative options.

**Comment by varmab** [comment]
We can write a program to resize existing images which does not require any manual effort image by image. However, I will check how they appearing in mobile with small size vs large size and will check how much quality is degrading between both sizes. it will give some perspective on how much we can reduce without loosing reader's experience.
