### ISSUE TITLE
Create Promo Codes

### ISSUE THREAD

**Issue by leematsunami** [varmab/mangahub#29]
We need to add the ability to provide codes to users so that they can be subscribed at no cost.

Their steps would include:

- Open app
- Go to profile
- Click on an option to enter a promo code (this should be a new menu item "Promo Code")
- Enter code and submit
- We validate authenticity
- User is now subscribed

On start up of app, we need to validate their code every time.
(mangamo can invalidate the code at any time so that user is unsubscribed)

The codes will be generated by us via database scripts.

@mangamojad please add to/revise this as you see fit!

**Comment by varmab** [comment]
It requires some research on how to use promo code in to in-app purchase in addition to above UI chanages. I am estimate it around 8 hours.

**Comment by varmab** [comment]
Approach 

1. Add promo code table in postgres to store promo codes
2. When user enter promo code, verify against table
3. If verified, allow user to watch mangas as they are like itunes subscribed  users
4. When promo code removed, App will verify and remove the access

**Comment by leematsunami** [comment]
On iPhone 11 Pro the HELP button is cut off. Please see attached.![promo_code_200317.png](https://images.zenhubusercontent.com/5e26534452024f09eb4b6d5c/a1dc7c5b-354f-4b56-aa82-556acf048682)

**Comment by varmab** [comment]
Released new version to TestFlight
