### ISSUE TITLE
Publisher Payment Data Dump: Revisions

### ISSUE THREAD

**Issue by leematsunami** [varmab/mangahub#30]
- Add Series ID and Publisher ID

- Add chapter data to dump

- Separate Total Page Views (PV) Pool by Active User Pool and Inactive Users Pool
  1.Active Users defined as UserS who have opened The Reader and read one or more manga pages that month
  2. Inactive Users defined as UserS who have not opened the Reader and read manga in that month
  3. List PVs from only the Active User Pool in the Page View breakdown

**Comment by varmab** [comment]
//Query
select P.id as PublisherID, P.name as Publisher,S.id as SeriesID,S.name as Series,C.chapterNumber as Chapter,count(U.eventtype) as TotalPV,round((count(U.eventtype)/ (select count(U.eventtype) as TotalCount from public.userevent U
where eventtype='page_opened' AND EXTRACT(MONTH FROM U.timestamp)=11 AND EXTRACT(YEAR FROM U.timestamp)=2019
)::numeric) *100,2) as PercentagePV,count(DISTINCT U.userid) as ActiveUsers
from public.userevent U
inner join public.chapter C ON C.id=U.chapterid
inner join public.series S ON S.id=C.seriesid
inner join public.publishertoseries PS ON ps.seriesid=S.id
inner join public.publisher P ON p.id=ps.publisherid
where eventtype='page_opened'
AND EXTRACT(MONTH FROM U.timestamp)=1 AND EXTRACT(YEAR FROM U.timestamp)=2020
GROUP BY eventtype,P.name,P.id,S.name,S.id,C.chapternumber
ORDER BY P.name,S.name,C.chapternumber DESC

**Comment by varmab** [comment]
[https://app.zenhub.com/files/216044275/ddafefc2-7b3e-42b1-9dde-319c56e55b08/download](https://app.zenhub.com/files/216044275/ddafefc2-7b3e-42b1-9dde-319c56e55b08/download)

**Comment by buddymanga** [comment]
Revisions required after review of 2/25 version.

1. Column G must add up to 100%. currently, it does not.
2. We need the following data monthly. Example:
Total Paying Subscribers 100
Active Users  82
Inactive Users  18
(active users defined as users who accessed at least one manga page that month. Inactive users defined as users who have not accessed any pages. These two should add up to Total Paying Subscribers)
3. Chapter ID must be 2 or 3 digits
Series ID must be 4 digits (1000 or above)

**Comment by varmab** [comment]
Here is revised data. No issue found in query. I found that one report I seem to put wrong year when running report for specific months. Percentages are now correct. 

[https://app.zenhub.com/files/216044275/69a76469-cd21-4de7-b75d-871c7ed202f8/download](https://app.zenhub.com/files/216044275/69a76469-cd21-4de7-b75d-871c7ed202f8/download)

**Comment by varmab** [comment]
Here is revised dump with Publisher and Series IDs

[https://app.zenhub.com/files/216044275/41a1000e-2374-446f-80cd-5fe10fe6896a/download](https://app.zenhub.com/files/216044275/41a1000e-2374-446f-80cd-5fe10fe6896a/download)

**Comment by buddymanga** [comment]
Need revised publisher payment dump with Publisher ID, Series ID, Chapter ID
Each ID should be 4-digits total.

**Comment by varmab** [comment]
select 
CASE 	WHEN P.id>99 THEN 'P' || P.id::text
		WHEN P.id>9 THEN 'P0' || P.id::text
		ELSE 'P00' || P.id::text
END as PublisherID,
P.name as Publisher,
CASE 	WHEN S.id>99 THEN 'S' || S.id::text
		WHEN S.id>9 THEN 'S0' || S.id::text
		ELSE 'S00' || S.id::text
END as SeriesID,
S.name as Series,
CASE 	WHEN C.chapterNumber>99 THEN 'C' || C.chapterNumber::text
		WHEN C.chapterNumber>9 THEN 'C0' || C.chapterNumber::text
		ELSE 'C00' || C.chapterNumber::text
END as ChaperID,
count(U.eventtype) as TotalPV,round((count(U.eventtype)/ (select count(U.eventtype) as TotalCount from public.userevent U
where eventtype='page_opened' AND EXTRACT(MONTH FROM U.timestamp)=11 AND EXTRACT(YEAR FROM U.timestamp)=2019
)::numeric) *100,2) as PercentagePV,count(DISTINCT U.userid) as ActiveUsers
from public.userevent U
inner join public.chapter C ON C.id=U.chapterid
inner join public.series S ON S.id=C.seriesid
inner join public.publishertoseries PS ON ps.seriesid=S.id
inner join public.publisher P ON p.id=ps.publisherid
where eventtype='page_opened'
AND EXTRACT(MONTH FROM U.timestamp)=11 AND EXTRACT(YEAR FROM U.timestamp)=2019
GROUP BY eventtype,P.name,P.id,S.name,S.id,C.chapternumber
ORDER BY P.name,S.name,C.chapternumber DESC

**Comment by varmab** [comment]
Here is the latest report 

[https://app.zenhub.com/files/216044275/382699cb-cda4-4102-b52e-84bacc946c63/download](https://app.zenhub.com/files/216044275/382699cb-cda4-4102-b52e-84bacc946c63/download)

**Comment by varmab** [comment]
Added 1 hr to estimate to log for changes.

**Comment by varmab** [comment]
1.  Make IDs are 5 digits (example: P0013)
2. Make %PV to 4 decimals (example: 1.9054)

**Comment by varmab** [comment]
select
CASE WHEN P.id>99 THEN 'P0' || P.id::text
WHEN P.id>9 THEN 'P00' || P.id::text
ELSE 'P000' || P.id::text
END as PublisherID,
P.name as Publisher,
CASE WHEN S.id>99 THEN 'S0' || S.id::text
WHEN S.id>9 THEN 'S00' || S.id::text
ELSE 'S000' || S.id::text
END as SeriesID,
S.name as Series,
CASE WHEN C.chapterNumber>99 THEN 'C0' || C.chapterNumber::text
WHEN C.chapterNumber>9 THEN 'C00' || C.chapterNumber::text
ELSE 'C000' || C.chapterNumber::text
END as ChaperID,
count(U.eventtype) as TotalPV,round((count(U.eventtype)/ (select count(U.eventtype) as TotalCount from public.userevent U
where eventtype='page_opened' AND EXTRACT(MONTH FROM U.timestamp)=11 AND EXTRACT(YEAR FROM U.timestamp)=2019
)::numeric) *100,4) as PercentagePV,count(DISTINCT U.userid) as ActiveUsers
from public.userevent U
inner join public.chapter C ON C.id=U.chapterid
inner join public.series S ON S.id=C.seriesid
inner join public.publishertoseries PS ON ps.seriesid=S.id
inner join public.publisher P ON p.id=ps.publisherid
where eventtype='page_opened'
AND EXTRACT(MONTH FROM U.timestamp)=11 AND EXTRACT(YEAR FROM U.timestamp)=2019
GROUP BY eventtype,P.name,P.id,S.name,S.id,C.chapternumber
ORDER BY P.name,S.name,C.chapternumber DESC

**Comment by varmab** [comment]
[https://app.zenhub.com/files/216044275/47da637a-219a-490a-b801-227828597bde/download](https://app.zenhub.com/files/216044275/47da637a-219a-490a-b801-227828597bde/download)
