### ISSUE TITLE
Chapter numbers showing wrong

### ISSUE THREAD

**Issue by buddymanga** [varmab/mangahub#7]
Reader: Chapter number is showing wrong (ex. Chapter 608)

![IMG_5549.jpg](https://images.zenhubusercontent.com/5dacfe023243eb00015ca0a5/a492edb2-86c4-4229-a5b5-b2af3b8093eb)

**Comment by varmab** [comment]
Does this mean, You want chapter numbers need to start from 1?

**Comment by buddymanga** [comment]
This only happens in the Reader Menu PAGES screen.
The Chapter number is random (Chapter 608 in the image example—there are not 608 chapters in this series!).
This Chapter number needs to match the current Chapter that the User is reading.

--
buddy marini | ceo
mangamo inc
m +81 90 5769 6688
www.mangamo.com
